<?php
return [
	'view'=>[
		'list'=>"jiny-menu::submenu.list"
	],
	'items'=>[
		'0'=>[
			'id'=>"1",
			'created_at'=>"",
			'updated_at'=>"",
			'code'=>"arduino",
			'menu_id'=>"0",
			'enable'=>"",
			'header'=>"",
			'title'=>"",
			'name'=>"아두이노",
			'icon'=>"",
			'href'=>"",
			'target'=>"",
			'selected'=>"",
			'submenu'=>"",
			'ref'=>"0",
			'level'=>"0",
			'pos'=>"1",
			'description'=>"",
			'user_id'=>"0"
		],
		'1'=>[
			'id'=>"2",
			'created_at'=>"",
			'updated_at'=>"",
			'code'=>"arduino",
			'menu_id'=>"0",
			'enable'=>"",
			'header'=>"",
			'title'=>"",
			'name'=>"프로젝트",
			'icon'=>"",
			'href'=>"",
			'target'=>"",
			'selected'=>"",
			'submenu'=>"",
			'ref'=>"0",
			'level'=>"0",
			'pos'=>"1",
			'description'=>"",
			'user_id'=>"0"
		],
		'2'=>[
			'id'=>"3",
			'created_at'=>"2024-05-13 06:24:55",
			'updated_at'=>"2024-05-13 06:25:39",
			'code'=>"arduino",
			'menu_id'=>"0",
			'enable'=>"",
			'header'=>"",
			'title'=>"",
			'name'=>"공모전2",
			'icon'=>"",
			'href'=>"",
			'target'=>"",
			'selected'=>"",
			'submenu'=>"",
			'ref'=>"0",
			'level'=>"0",
			'pos'=>"1",
			'description'=>"",
			'user_id'=>"0"
		],
		''=>[
			'updated_at'=>"2024-05-13 06:25:39"
		]
	]
];